### ISSUE TITLE
Error in version 1.1.5

### ISSUE THREAD

**Issue by pajeronda** [patrickkfkan/volumio-youtube2#14]
info: CoreCommandRouter::executeOnPlugin: youtube2 , handleBrowseUri
Mar 28 07:47:47 volumio volumio[797]: info: [youtube2-browse] browseUri: youtube2/generic@endpoint:o=%7B%22type%22%3A%22browse%22%2C%22payload%22%3A%7B%22browseId%22%3A%22VLPL-VGbn5yWv3Ew8DJGqB5nXy6xc3OdBY9P%22%7D%7D
Mar 28 07:47:47 volumio volumio[797]: InnertubeError: Something went wrong at SortFilterHeader!
Mar 28 07:47:47 volumio volumio[797]: This is a bug, please report it at https://github.com/patrickkfkan/Volumio-YouTube.js/issues
Mar 28 07:47:47 volumio volumio[797]:     at Function._Parser_printError (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18226:16)
Mar 28 07:47:47 volumio volumio[797]:     at Function.parseItem (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18059:70)
Mar 28 07:47:47 volumio volumio[797]:     at new ItemSection (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:13950:34)
Mar 28 07:47:47 volumio volumio[797]:     at Function.parseItem (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)
Mar 28 07:47:47 volumio volumio[797]:     at Function.parseArray (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18069:29)
Mar 28 07:47:47 volumio volumio[797]:     at new SectionList (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:16343:36)
Mar 28 07:47:47 volumio volumio[797]:     at Function.parseItem (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)
Mar 28 07:47:47 volumio volumio[797]:     at new Tab (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:16592:35)
Mar 28 07:47:47 volumio volumio[797]:     at Function.parseItem (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)
Mar 28 07:47:47 volumio volumio[797]:     at Function.parse (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18086:29)
Mar 28 07:47:47 volumio volumio[797]:     at new TwoColumnBrowseResults (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:16943:32)
Mar 28 07:47:47 volumio volumio[797]:     at Function.parseItem (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)
Mar 28 07:47:47 volumio volumio[797]:     at Function.parse (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18096:39)
Mar 28 07:47:47 volumio volumio[797]:     at Function.parseResponse (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:17864:27)
Mar 28 07:47:47 volumio volumio[797]:     at EndpointModel._EndpointModel_doGetContents (/data/plugins/music_service/youtube2/dist/lib/model/EndpointModel.js:39:49)
Mar 28 07:47:47 volumio volumio[797]:     at processTicksAndRejections (internal/process/task_queues.js:93:5) {
Mar 28 07:47:47 volumio volumio[797]:   info: {
Mar 28 07:47:47 volumio volumio[797]:     stack: 'Error: Type mismatch, got SortFilterHeader but expected one of CommentsHeader, ItemSectionHeader, ItemSectionTabbedHeader\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at Function.parseItem (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18051:21)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at new ItemSection (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:13950:34)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at Function.parseItem (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at Function.parseArray (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18069:29)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at new SectionList (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:16343:36)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at Function.parseItem (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at new Tab (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:16592:35)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at Function.parseItem (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at Function.parse (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18086:29)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at new TwoColumnBrowseResults (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:16943:32)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at Function.parseItem (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at Function.parse (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18096:39)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at Function.parseResponse (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:17864:27)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at EndpointModel._EndpointModel_doGetContents (/data/plugins/music_service/youtube2/dist/lib/model/EndpointModel.js:39:49)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
Mar 28 07:47:47 volumio volumio[797]:       '    at async GenericViewHandler.getContents (/data/plugins/music_service/youtube2/dist/lib/controller/browse/view-handlers/GenericViewHandler.js:44:26)'
Mar 28 07:47:47 volumio volumio[797]:   },
Mar 28 07:47:47 volumio volumio[797]:   date: 2024-03-28T06:47:47.879Z,
Mar 28 07:47:47 volumio volumio[797]:   version: '0.3.3'
Mar 28 07:47:47 volumio volumio[797]: }

**Comment by patrickkfkan** [comment]
These parser errors are kind of inevitable, but should not affect functionality. So the question is: has this affected your usage of the plugin?

**Comment by pajeronda** [comment]
Hi @patrickkfkan 
While I'm listening to a song, randomly the listening stops and neither goes to the previous or next song. Where do I start? the problem occurs with all three of your plugins (cast, TouTube2, Youtube Music). The plugins are at the latest version available.

**Comment by patrickkfkan** [comment]
Closing as no longer relevant
