### ISSUE TITLE
No sound when a video is played on volumio: VideoModel.getInfo():  Unexpected token (1:47)

### ISSUE THREAD

**Issue by cmoulliard** [patrickkfkan/volumio-youtube2#15]
## Issue

I have installed the plugin YouTube2 and been able to sign. When I select a video from youtube and click on the button to listen to the video, I cannot hear it and log report the following error

Volumio version: 3.301
Youtube2 version: 1.2.2

Log report:
```
Sep 17 06:26:54 volumio volumio[754]: info: [youtube2-play] clearAddPlayTrack: youtube2/video@endpoint:o=%7B%22type%22%3A%22watch%22%2C%22payload%22%3A%7B%22videoId%22%3A%22QJAw1ccUiQk%22%2C%22playlistId%22%3A%22PLxJJcP5YX06czVMZVd5nE5vaSkttqjFHY%22%2C%22params%22%3A%22OAE%253D%22%2C%22index%22%3A0%7D%7D@explodeTrackData:o=%7B%22title%22%3A%22The%20Pusher%20feat.%20Chris%20Robinson%22%2C%22artist%22%3A%22Slash%22%2C%22albumart%22%3A%22https%3A%2F%2Fi.ytimg.com%2Fvi%2FQJAw1ccUiQk%2Fhqdefault.jpg%3Fsqp%3D-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg%3D%3D%26rs%3DAOn4CLA8wR0Qj87ndsbAzKML7bdKpR1spQ%22%2C%22endpoint%22%3A%7B%22type%22%3A%22watch%22%2C%22payload%22%3A%7B%22videoId%22%3A%22QJAw1ccUiQk%22%2C%22playlistId%22%3A%22PLxJJcP5YX06czVMZVd5nE5vaSkttqjFHY%22%2C%22params%22%3A%22OAE%253D%22%2C%22index%22%3A0%7D%7D%7D
Sep 17 06:26:54 volumio volumio[754]: info: [youtube2] InnertubeLoader: creating Innertube instance...
Sep 17 06:26:54 volumio volumio[754]: info: CoreCommandRouter::executeOnPlugin: my_volumio , getMyVolumioStatus
Sep 17 06:26:54 volumio volumio[754]: info: [youtube2] InnertubeLoader: creating Auth instance...
Sep 17 06:26:54 volumio volumio[754]: info: CoreCommandRouter::getUIConfigOnPlugin
Sep 17 06:26:54 volumio volumio[754]: info: CoreCommandRouter::getUIConfigOnPlugin
Sep 17 06:26:54 volumio volumio[754]: info: [youtube2] InnertubeLoader: Auth instance created (status: signed in)
Sep 17 06:26:54 volumio volumio[754]: info: CoreCommandRouter::executeOnPlugin: my_volumio , getMyVolumioStatus
Sep 17 06:26:55 volumio volumio[754]: error: [youtube2] Error in VideoModel.getInfo(QJAw1ccUiQk):  Unexpected token (1:47) SyntaxError: Unexpected token (1:47)
Sep 17 06:26:55 volumio volumio[754]:     at Parser.pp$4.raise (/data/plugins/music_service/youtube2/node_modules/acorn/dist/acorn.js:3553:15)
Sep 17 06:26:55 volumio volumio[754]:     at Parser.pp$9.unexpected (/data/plugins/music_service/youtube2/node_modules/acorn/dist/acorn.js:764:10)
Sep 17 06:26:55 volumio volumio[754]:     at Parser.pp$9.semicolon (/data/plugins/music_service/youtube2/node_modules/acorn/dist/acorn.js:741:68)
Sep 17 06:26:55 volumio volumio[754]:     at Parser.pp$8.parseVarStatement (/data/plugins/music_service/youtube2/node_modules/acorn/dist/acorn.js:1178:10)
Sep 17 06:26:55 volumio volumio[754]:     at Parser.pp$8.parseStatement (/data/plugins/music_service/youtube2/node_modules/acorn/dist/acorn.js:919:19)
Sep 17 06:26:55 volumio volumio[754]:     at Parser.pp$8.parseBlock (/data/plugins/music_service/youtube2/node_modules/acorn/dist/acorn.js:1246:23)
Sep 17 06:26:55 volumio volumio[754]:     at Parser.pp$5.parseFunctionBody (/data/plugins/music_service/youtube2/node_modules/acorn/dist/acorn.js:3374:24)
Sep 17 06:26:55 volumio volumio[754]:     at Parser.pp$8.parseFunction (/data/plugins/music_service/youtube2/node_modules/acorn/dist/acorn.js:1368:10)
Sep 17 06:26:55 volumio volumio[754]:     at Parser.pp$8.parseFunctionStatement (/data/plugins/music_service/youtube2/node_modules/acorn/dist/acorn.js:1062:17)
Sep 17 06:26:55 volumio volumio[754]:     at Parser.pp$8.parseStatement (/data/plugins/music_service/youtube2/node_modules/acorn/dist/acorn.js:907:19)
Sep 17 06:26:55 volumio volumio[754]:     at Parser.pp$8.parseTopLevel (/data/plugins/music_service/youtube2/node_modules/acorn/dist/acorn.js:821:23)
Sep 17 06:26:55 volumio volumio[754]:     at Parser.parse (/data/plugins/music_service/youtube2/node_modules/acorn/dist/acorn.js:593:17)
Sep 17 06:26:55 volumio volumio[754]:     at Function.parse (/data/plugins/music_service/youtube2/node_modules/acorn/dist/acorn.js:643:37)
Sep 17 06:26:55 volumio volumio[754]:     at parse (/data/plugins/music_service/youtube2/node_modules/acorn/dist/acorn.js:5942:19)
Sep 17 06:26:55 volumio volumio[754]:     at new Jinter (/data/plugins/music_service/youtube2/node_modules/jintr/bundle/jinter.cjs:999:44)
Sep 17 06:26:55 volumio volumio[754]:     at Object.evaluate [as eval] (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:21633:19)
```

Full log: http://logs.volumio.org/volumio/ZdHTw3h.html

Additional errors are also reported within the full log like 
```
Sep 17 06:31:03 volumio volumio[754]: CommentsSimplebox not found!
Sep 17 06:31:03 volumio volumio[754]: This is a bug, want to help us fix it? Follow the instructions at https://github.com/patrickkfkan/Volumio-YouTube.js/blob/main/docs/updating-the-parser.md or report it at https://github.com/patrickkfkan/Volumio-YouTube.js/issues!
Sep 17 06:31:03 volumio volumio[754]: Introspected and JIT generated this class in the meantime:
Sep 17 06:31:03 volumio volumio[754]: class CommentsSimplebox extends YTNode {
Sep 17 06:31:03 volumio volumio[754]:   static type = 'CommentsSimplebox';
Sep 17 06:31:03 volumio volumio[754]:   simplebox_avatar: Thumbnail[];
Sep 17 06:31:03 volumio volumio[754]:   simplebox_placeholder: Text;
Sep 17 06:31:03 volumio volumio[754]:   constructor(data: RawNode) {
Sep 17 06:31:03 volumio volumio[754]:     super();
Sep 17 06:31:03 volumio volumio[754]:     this.simplebox_avatar = Thumbnail.fromResponse(data.simpleboxAvatar);
Sep 17 06:31:03 volumio volumio[754]:     this.simplebox_placeholder = new Text(data.simpleboxPlaceholder);
Sep 17 06:31:03 volumio volumio[754]:   }
Sep 17 06:31:03 volumio volumio[754]: }
Sep 17 06:31:03 volumio volumio[754]: InnertubeError: Something went wrong at CommentsSimplebox!
Sep 17 06:31:03 volumio volumio[754]: This is a bug, please report it at https://github.com/patrickkfkan/Volumio-YouTube.js/issues
Sep 17 06:31:03 volumio volumio[754]:     at Function._Parser_printError (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18226:16)
Sep 17 06:31:03 volumio volumio[754]:     at Function.parseItem (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18059:70)
Sep 17 06:31:03 volumio volumio[754]:     at new CommentsEntryPointHeader (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:12558:47)
Sep 17 06:31:03 volumio volumio[754]:     at Function.parseItem (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)
Sep 17 06:31:03 volumio volumio[754]:     at Function.parseArray (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18069:29)
Sep 17 06:31:03 volumio volumio[754]:     at new ItemSection (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:13951:36)
Sep 17 06:31:03 volumio volumio[754]:     at Function.parseItem (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)
Sep 17 06:31:03 volumio volumio[754]:     at Function.parseArray (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18069:29)
Sep 17 06:31:03 volumio volumio[754]:     at new TwoColumnWatchNextResults (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:16971:35)
Sep 17 06:31:03 volumio volumio[754]:     at Function.parseItem (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18055:24)
Sep 17 06:31:03 volumio volumio[754]:     at Function.parse (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:18096:39)
Sep 17 06:31:03 volumio volumio[754]:     at Function.parseResponse (/data/plugins/music_service/youtube2/node_modules/volumio-youtubei.js/bundle/node.cjs:17864:27)
Sep 17 06:31:03 volumio volumio[754]:     at EndpointModel._EndpointModel_doGetContents (/data/plugins/music_service/youtube2/dist/lib/model/EndpointModel.js:39:49)
Sep 17 06:31:03 volumio volumio[754]:     at runMicrotasks ()
Sep 17 06:31:03 volumio volumio[754]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)
Sep 17 06:31:03 volumio volumio[754]:     at async GenericViewHandler.getTracksOnExplode (/data/plugins/music_service/youtube2/dist/lib/controller/browse/view-handlers/GenericViewHandler.js:97:26) {
Sep 17 06:31:03 volumio volumio[754]:   info: {
```

**Comment by patrickkfkan** [comment]
Fixed in v1.3.3
